assembly_linkage.o: assembly_linkage.S assembly_linkage.h
boot.o: boot.S multiboot.h x86_desc.h types.h idt.h
x86_desc.o: x86_desc.S x86_desc.h types.h
filesystem.o: filesystem.c filesystem.h types.h lib.h rtc.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h assembly_linkage.h x86_desc.h types.h lib.h keyboard.h \
  rtc.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h rtc.h keyboard.h paging.h filesystem.h
keyboard.o: keyboard.c keyboard.h lib.h types.h i8259.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h x86_desc.h types.h
rtc.o: rtc.c rtc.h lib.h types.h i8259.h tests.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h filesystem.h
